version: '3'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_NAME=test_db
      - DB_USER=test_user
      - DB_PASSWORD=password

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password